on:
  pull_request:
    branches:
      - $default-branch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
